### ISSUE TITLE
Article Extraction

### ISSUE THREAD

**Issue by PandaWhoCodes** [1hef001/NewsCluster#4]
Use third party tools for article extraction.
Your current method gives a lot to be desired and empty results in certain websites.
Scraping the way we do will not be possible for certain website , especially the onces that load content on DOM load like angluar apps. You might want to blacklist those websites.

**Comment by 1hef001** [comment]
A python package "[newspaper](https://newspaper.readthedocs.io/en/latest/)" is being used for extraction of articles.
