### ISSUE TITLE
Stores news in a database

### ISSUE THREAD

**Issue by PandaWhoCodes** [1hef001/NewsCluster#5]
I see you have written code for database usage, but on download news articles you save it to text files. Is there a reason you havent yet implemented the code for sqlite db you wrote ?

**Comment by 1hef001** [comment]
The [latest commit](https://github.com/1hef001/NewsCluster/commit/3b3f4ccbd9f18865627eddc61019246c730efccd) stores the news and headlines in a database using sql.
